import { activityTypes } from './activityTypes'

export const editable = [
    'Sleep',
    'Sex',
    'Toilet',
    'Syncope',
    'Shower',
    'NormalWalking',
    'Bicycling',
    'Running',
    'Meal',
    'Meal',
    'Alcohol',
    // 'Trainer', // add edit functionality to the screen
    'Smoking',
    'ReliefOfAttack',
    'CourseTherapy',
    'Headache',
    'RetrosternalPain',
    'HeartAreaPain',
    'Palpitation',
    'Arrhythmia',
    'Dyspnea',
    'Tachypnea',
    'Nausea',
    'Stupefaction',
    'VisionDisturbances',
    'Positive',
    'Negative',
    'OtherLoad',
    'OtherActivity',
    'OtherEmotions',
    'OtherPain',
    'OtherComplaints',
    'OtherWeakness',
    'Workout',
    'Fatigue',
    'DeepBreathing',
    'Straining',
    'PsychoemotionalTest',
    'CuffFix',
    'ElectrodeReplacement',
]
