import { activityTypes } from './activityTypes'

export const editable = [
    'Sleep',
    'Sex',
    'Toilet',
    'Syncope',
    'Shower',
    'GymWalking',
    'Bicycling',
    'Running',
    'Meal',
    'Meal',
    'Alcohol',
    'Gym',
    'Smoking',
    'ReliefOfAttack',
    'CourseTherapy',
    'Headache',
    'RetrosternalPain',
    'HeartAreaPain',
    'Palpitation',
    'Arrhythmia',
    'Dyspnea',
    'Tachypnea',
    'Faint',
    'Stupefaction',
    'VisionDisturbances',
    'Positive',
    'Negative',
    'OtherLoad',
    'OtherActivity',
    'OtherEmotions',
    'OtherPain',
    'OtherComplaints',
    'OtherWeakness',
]
