export const overlaps = {
    Sleep: [
        'Walking',
        'NormalWalking',
        'Running',
        'Bicycle',
        'Trainer',
        'Sleep',
        'OtherLoad',
        'Meal',
        'Alcohol',
        'Smoking',
        'Sex',
        'Toilet',
        'Shower',
        'OtherActivity',
    ],
    PhysicalLoad: [
        'Sleep',
        'Meal',
        'Alcohol',
        'Smoking',
        'Sex',
        'Toilet',
        'Shower',
        'OtherActivity',
        'Walking',
        'NormalWalking',
        'Running',
        'Bicycle',
        'Trainer',
        'OtherLoad',
    ],
    Activity: [
        'Sleep',
        'Walking',
        'NormalWalking',
        'Running',
        'Bicycle',
        'Trainer',
        'OtherLoad',
        'Meal',
        'Alcohol',
        'Smoking',
        'Sex',
        'Toilet',
        'Shower',
        'OtherActivity',
    ],
    Pills: ['Sleep'],
    Tests: ['Sleep'],
    Service: ['Sleep'],
}
