import LocalizedStrings from 'react-native-localization'
import BloodPressure from './components/BloodPressure'

export const strings = new LocalizedStrings({
    'en-US': {
        Activity: 'Activity',
        ActivityEdit: 'Activity Edit',
        Alarm: 'Alarm',
        Alcohol: 'Alcohol',
        Alert: 'Alert',
        and: 'and',
        AppTitle: 'Cardio Journal',
        April: 'April',
        Arrhythmia: 'Arrhythmia',
        AskMeLater: 'Ask me later',
        at: 'at',
        AtivityStats: 'Activity statistics',
        August: 'August',
        Bad: 'Bad',
        Bicycling: 'Bicycling',
        Calibrating: 'Calibrating',
        Calories: 'Calories',
        CameraPermissions: 'Camera Permissions',
        CameraPermissionsMessage: 'Cardio Journal needs access to your camera',
        CamPermDenied: 'Camera permission denied',
        Cancel: 'Cancel',
        CantConnect: "Can't connect to the server,",
        CantGoBack: "Can't go back, you need to finish exercise first",
        Comment: 'Comment',
        Complaints: 'Disturbance of respiration',
        Complaints: 'Complaints',
        CourseTherapy: 'Course therapy',
        CuffFix: 'Cuff fix',
        December: 'December',
        DeviceId: 'Device id',
        DeviceInstall: 'Device installation',
        DeviceInstalled: 'Device installed',
        Distance: 'Distance',
        Drug: 'Pill',
        Duration: 'Duration',
        Dyspnea: 'Dyspnea',
        EditProfile: 'Edit profile',
        ElectrodeReplacement: 'Electrode replacement',
        EmotionalStress: 'Emotional stress',
        Error: 'Error',
        ErrQR: 'Error readying QR code',
        ExerciseFinish: 'Exercise finish',
        ExerciseFinishText: 'Good job! You completed the exercise!',
        Nausea: 'Nausea',
        Fatigue: 'Fatigue',
        February: 'February',
        Finish: 'Finish',
        FoundLocation: 'Location found!',
        FromEnd: 'From end',
        FromStart: 'From start',
        Good: 'Good',
        Trainer: 'Trainer',
        TrainerType: 'Exercise machine type',
        NormalWalking: 'Walking',
        HaveAGoodSleep: 'Have a good Sleep',
        Headache: 'Headache',
        HeartAreaPain: 'Heart area pain',
        Home: 'Home',
        hour: 'hour',
        hours: 'hours',
        HowDoYouFeelAfterThis: 'How do you feel after this?',
        idinv: 'Investigation ID',
        January: 'January',
        Journal: 'Journal',
        July: 'July',
        June: 'June',
        Locating: 'Looking for location!',
        LocationPermissions: 'Location Permissions',
        LocationPermissionsMessage:
            'Cardio Journal needs access to your location',
        Login: 'Login',
        Logout: 'Logout',
        March: 'March',
        May: 'May',
        Meal: 'Meal',
        MedicineTest: 'Medicine test',
        Meters: 'Meters',
        MicrophonePermissions: 'Microphone Permissions',
        MicrophonePermissionsMessage:
            'Cardio Journal needs access to your microphone',
        minute: 'minute',
        minutes: 'minutes',
        mmHg: 'mmHg',
        Nausea: 'Nausea',
        Negative: 'Negative',
        Negative: 'Negative',
        NoConn: 'No Connection',
        NoPhoto: 'No Photo',
        Normal: 'Normal',
        NotFilled: 'Not filled',
        notifText: 'Time to complete the exercise. Tap here to start!',
        NotSelected: 'Not selected',
        November: 'November',
        October: 'October',
        Ok: 'Ok',
        Orthostasis: 'Orthostasis',
        Other: 'Other',
        OtherActivity: 'Other activity',
        OtherComplaints: 'Other complaints',
        OtherEmotions: 'Other emotions',
        OtherLoad: 'Other load (Labor)',
        OtherPain: 'Other pain',
        OtherWeakness: 'Other weakness',
        OverlapMsg: "Can't add the activity, its overlapping with others,",
        OverlapTitle: 'Overlap',
        Pain: 'Pain',
        Palpitation: 'Palpitation',
        password: 'password',
        PhysicalLoad: 'Psysical load',
        PositionalChanges: 'Positional changes',
        Positive: 'Positive',
        Postponed: 'Postponed',
        Press: 'Press',
        Pressure: 'Pressure',
        Problems: 'Problems',
        PsychoemotionalTest: 'Psychoemotional test',
        Register: 'Register',
        ReliefOfAttack: 'Relief of attack',
        RemindLater: 'Remind later',
        RetrosternalPain: 'Retrosternal pain',
        Running: 'Running',
        Save: 'Save',
        Saved: 'Saved',
        September: 'September',
        Service: 'Service',
        Settings: 'Settings',
        Sex: 'Sex',
        Shower: 'Shower',
        Sleep: 'Sleep',
        Smoking: 'Smoking',
        Stairs: 'Stairs',
        Start: 'Start',
        Steps: 'Steps',
        StoragePermissions: 'Storage Permissions',
        StoragePermissionsMessage:
            'Cardio Journal needs access to your internal storage',
        Straining: 'Straining',
        Stupefaction: 'Stupefaction',
        Syncope: 'Syncope',
        Tachypnea: 'Tachypnea',
        TakePhoto: 'Take a photo',
        TakingMedicine: 'Medicine',
        Tasks: 'Tasks',
        Terminate: 'Terminate',
        TerminationExerciseQuestion:
            'Do you really want to terminate the exercise? It cannot be undone',
        Tests: 'Tests',
        Time: 'Time',
        Today: 'Today',
        Toilet: 'Toilet',
        Tomorrow: 'Tomorrow',
        Undefined: 'Undefined',
        username: 'username',
        Version: 'Version',
        VerticalPositionCalibration: 'Vertical Position Calibration',
        VisionDisturbances: 'Vision disturbances',
        Walking: '6 min walking test',
        Weakness: 'Weakness',
        WrongPassword: 'Wrong username or password',
        Yesterday: 'Yesterday',
        YouClimbed: 'You climbed',
        YouWalked: 'You walked',
        by: 'by',
        Cycling: 'Cycling',
        Elliptical: 'Elliptical',
        StairStepper: 'Stair-stepper',
        Joy: 'Joy',
        Sadness: 'Sadness',
        Anger: 'Anger',
        Fear: 'Fear',
        Excitement: 'Excitement',
        Anxiety: 'Anxiety',
        WeightLifting: 'Weight lifting',
        PhysicalLabor: 'Physical labor',
        Before: 'Before',
        After: 'After',
        BloodPressure: 'Blood pressure',
        NotFilledUp: 'Not filled up',
        Straight: 'Straight',
        LeaningForward: 'Leaning forward',
        LeaningToTheLeft: 'Leaning to the left',
    },
    es: {
        Activity: 'Actividad',
        ActivityEdit: 'Edición de la actividad',
        Alarm: 'Problema',
        Alcohol: 'Alcohol',
        Alert: 'Alerta',
        and: 'y',
        AppTitle: 'Diario de Cardio',
        April: 'Abril',
        Arrhythmia: 'Arritmia',
        AskMeLater: 'Pregúntame luego',
        at: 'a',
        AtivityStats: 'Estadísticas de actividad',
        August: 'Agosto',
        Bad: 'Mal',
        Bicycling: 'Montar en bicicleta',
        Calibrating: 'Calibración',
        Calories: 'Calorías',
        CameraPermissions: 'Permisos de сámera',
        CameraPermissionsMessage: 'Cardio Journal necesita acceso a tu cámara',
        CamPermDenied: 'Permiso de la cámara denegado',
        Cancel: 'Cancelar',
        CantConnect: 'No se puede conectar al servidor',
        CantGoBack: 'No puedes volver, necesitas terminar el ejercicio primero',
        Comment: 'Comentario',
        Complaints: 'Alteración de la respiración',
        Complaints: 'Quejas',
        CourseTherapy: 'Curso de terapia',
        CuffFix: 'Brazalete fijar',
        December: 'Diciembre',
        DeviceId: 'Identificación del dispositivo',
        DeviceInstall: 'Installación del despositivo',
        DeviceInstalled: 'Dispositivo instalado',
        Distance: 'Distancia',
        Drug: 'Postilla',
        Duration: 'Duración',
        Dyspnea: 'Disnea',
        EditProfile: 'Editar perfil',
        ElectrodeReplacement: 'Reemplazo de electrodos',
        EmotionalStress: 'Estrés emocional',
        Error: 'Error',
        ErrQR: 'Error al preparar el código QR',
        ExerciseFinish: 'Ejercicio finalizado',
        ExerciseFinishText: '¡Buen trabajo! ¡Has completado el ejercicio!',
        Nausea: 'Débil',
        Fatigue: 'Fatiga',
        February: 'Febrero',
        Finish: 'Terminar',
        FoundLocation: '¡Ubicación encontrada!',
        FromEnd: 'Del final',
        FromStart: 'Del principio',
        Good: 'Bien',
        Trainer: 'Gimnasio',
        TrainerType: 'Tipo de máquina de ejercicio',
        NormalWalking: 'Caminar',
        HaveAGoodSleep: 'Tener un buen descanso',
        Headache: 'Dolor de cabeza',
        HeartAreaPain: 'Dolor en área del corazón',
        Home: 'Principal',
        hour: 'hora',
        hours: 'horas',
        HowDoYouFeelAfterThis: '¿Cómo te sientes después de esto?',
        idinv: 'Identificación de investigación',
        January: 'Jenero',
        Journal: 'Diario',
        July: 'Julio',
        June: 'Junio',
        Locating: '¡Buscando ubicación!',
        LocationPermissions: 'Permisos de ubicación',
        LocationPermissionsMessage:
            'Cardio Journal necesita acceso a tu ubicación',
        Login: 'Entrar',
        Logout: 'Cerrar',
        March: 'Marso',
        May: 'Mayo',
        Meal: 'Comida',
        MedicineTest: 'Prueba de medicina',
        Meters: 'Metros',
        MicrophonePermissions: 'Permisos de micrófono',
        MicrophonePermissionsMessage:
            'Cardio Journal necesita acceso a tu micrófono',
        minute: 'minuto',
        minutes: 'minutos',
        mmHg: 'mmHg',
        Nausea: 'Náusea',
        Negative: 'Negativa',
        Negative: 'Negativa',
        NoConn: 'Sin conexión',
        NoPhoto: 'No hay foto',
        Normal: 'Normal',
        NotFilled: 'No llenado',
        notifText:
            'Tiempo para completar el ejercicio. Toque aquí para comenzar!',
        NotSelected: 'No seleccionado',
        November: 'Noviembre',
        October: 'Octubre',
        Ok: 'Ok',
        Orthostasis: 'Ortostasis',
        Other: 'Otra',
        OtherActivity: 'Otra actividad',
        OtherComplaints: 'Otras quejas',
        OtherEmotions: 'Otras emociones ',
        OtherLoad: 'Otra carga',
        OtherPain: 'Otro dolor',
        OtherWeakness: 'Otra debilidad',
        OverlapMsg:
            'No es possible agregar la actividad, se superpone con otras',
        OverlapTitle: 'Superposición',
        Pain: 'Dolor',
        Palpitation: 'Palpitación',
        password: 'contraseña',
        PhysicalLoad: 'Carga fisica',
        PositionalChanges: 'Cambios posicionales',
        Positive: 'Positiva',
        Postponed: 'Pospuesto',
        Press: 'Presión',
        Pressure: 'Presión',
        Problems: 'Problemas',
        PsychoemotionalTest: 'Prueba psicoemocional',
        Register: 'Registrarse',
        ReliefOfAttack: 'Alivio del ataque',
        RemindLater: 'Recordar mas tarde',
        RetrosternalPain: 'Dolor retrosternal',
        Running: 'Corriendo',
        Save: 'Salvar',
        Saved: 'Salvado',
        September: 'Septiembre',
        Service: 'Servicio',
        Settings: 'Configuraciones',
        Sex: 'Sexo',
        Shower: 'Ducha',
        Sleep: 'Dormir',
        Smoking: 'Fumar',
        Stairs: 'Escalera',
        Start: 'Comenzar',
        Steps: 'Pasas',
        StoragePermissions: 'Permisos de almacenamiento',
        StoragePermissionsMessage:
            'Cardio Journal necesita acceso a tu almacenamiento',
        Straining: 'Tirante',
        Stupefaction: 'Estupefacción',
        Syncope: 'Síncope',
        Tachypnea: 'Taquipnea',
        TakePhoto: 'Tomar un foto',
        TakingMedicine: 'Pastillas',
        Tasks: 'Tareas',
        Terminate: 'Terninar',
        TerminationExerciseQuestion:
            '¿Realmente quieres terminar el ejercicio? No se puede deshacer',
        Tests: 'Pruebas',
        Time: 'Tiempo',
        Today: 'Hoy',
        Toilet: 'Baño',
        Tomorrow: 'Mañana',
        Undefined: 'Indefinida',
        username: 'nombre de usuario',
        Version: 'Versión',
        VerticalPositionCalibration: 'Calibración de posición vertical',
        VisionDisturbances: 'Trastornos de la visión',
        Walking: 'Prueba de caminata de 6 min',
        Weakness: 'Debilidad',
        WrongPassword: 'Nombre de usuario o contraseña incorrectos',
        Yesterday: 'Ayer',
        YouClimbed: 'Usted subió',
        YouWalked: 'Usted caminó',
        by: 'por',
        Cycling: 'Cycling',
        Elliptical: 'Elliptical',
        StairStepper: 'StairStepper',
        Joy: 'Joy',
        Sadness: 'Sadness',
        Anger: 'Anger',
        Fear: 'Fear',
        Excitement: 'Excitement',
        Anxiety: 'Anxiety',
        WeightLifting: 'Weight lifting',
        PhysicalLabor: 'Physical labor',
        Before: 'Before',
        After: 'After',
        BloodPressure: 'Blood pressure',
        NotFilledUp: 'Not filled up',
        Straight: 'Straight',
        LeaningForward: 'Leaning forward',
        LeaningToTheLeft: 'Leaning to the left',
    },
    ru: {
        Activity: 'Активность',
        ActivityEdit: 'Редактирование активности',
        Alarm: 'Тревога',
        Alcohol: 'Алкоголь',
        Alert: 'Внимание',
        and: 'и',
        AppTitle: 'Кардио журнал',
        April: 'Апреля',
        Arrhythmia: 'Перебои (аритмия)',
        AskMeLater: 'Спросить позже',
        at: 'в',
        AtivityStats: 'Статистика активности',
        August: 'Августа',
        Bad: 'Плохо',
        Bicycling: 'Велосипед',
        Calibrating: 'Калибровка',
        Calories: 'Калории',
        CameraPermissions: 'Разрешение на использование камеры',
        CameraPermissionsMessage: 'Cardio Journal нужен доступ к камере',
        CamPermDenied: 'Отказано в использовании камеры',
        Cancel: 'Отменить',
        CantConnect: 'Невозможно соединиться с сервером',
        CantGoBack: 'Нельзя вернуться, сначала закончите занятие',
        Comment: 'Комментарий',
        Complaints: 'Нарушения дыхания',
        Complaints: 'Жалобы',
        CourseTherapy: 'Курсовая терапия',
        CuffFix: 'Поправка манжеты',
        December: 'Декабря',
        DeviceId: 'Номер устройства',
        DeviceInstall: 'Установка прибора',
        DeviceInstalled: 'Устройство установлено',
        Distance: 'Расстояние',
        Drug: 'Препарат',
        Duration: 'Длительность',
        Dyspnea: 'Одышка',
        EditProfile: 'Редактировать профиль',
        ElectrodeReplacement: 'Замена электрода',
        EmotionalStress: 'Эмоциональная нагрузка',
        Error: 'Ошибка',
        ErrQR: 'Не удаётся прочесть QR код',
        ExerciseFinish: 'Завершение затяния',
        ExerciseFinishText: 'Поздравляем, вы справились с занятием!',
        Nausea: 'Дурнота',
        Fatigue: 'Усталость',
        February: 'Февраля',
        Finish: 'Завершить',
        FoundLocation: 'Местоположение найдено!',
        FromEnd: 'Время конца',
        FromStart: 'Время начала',
        Good: 'Хорошо',
        Trainer: 'Тренажёр',
        TrainerType: 'Тип тренажёра',
        NormalWalking: 'Ходьба',
        HaveAGoodSleep: 'Приятного отдыха',
        Headache: 'Головная боль',
        HeartAreaPain: 'Боль в области сердца',
        Home: 'Дом',
        hour: 'час',
        hours: 'часов',
        HowDoYouFeelAfterThis: 'Как вы себя чувствуете после этого?',
        idinv: 'Номер обследования',
        January: 'Января',
        Journal: 'Дневник',
        July: 'Июля',
        June: 'Июня',
        Locating: 'Поиск местоположения!',
        LocationPermissions: 'Разрешение на использование геолокации',
        LocationPermissionsMessage: 'Cardio Journal нужен доступ к геолокации',
        Login: 'Войти',
        Logout: 'Выйти',
        March: 'Марта',
        May: 'Мая',
        Meal: 'Еда',
        MedicineTest: 'Тестируемый препарат',
        Meters: 'Метров',
        MicrophonePermissions: 'Разрешение на использование микрофона',
        MicrophonePermissionsMessage: 'Cardio Journal нужен доступ к микрофону',
        minute: 'минута',
        minutes: 'минут',
        mmHg: 'мм рт.ст.',
        Nausea: 'Тошнота',
        Negative: 'Негативная',
        Negative: 'Негативная',
        NoConn: 'Нет соединения',
        NoPhoto: 'Нет фото',
        Normal: 'Нормально',
        NotFilled: 'Не заполнено',
        notifText: 'Время выполнить задание. Нажмите, чтобы начать!',
        NotSelected: 'Не выбрано',
        November: 'Ноября',
        October: 'Октября',
        Ok: 'Ок',
        Orthostasis: 'Ортостаз',
        Other: 'Другое',
        OtherActivity: 'Другая активность',
        OtherComplaints: 'Другие жалобы',
        OtherEmotions: 'Другие эмоции',
        OtherLoad: 'Другая нагрузка (работа)',
        OtherPain: 'Другая боль',
        OtherWeakness: 'Другое',
        OverlapMsg: 'Невозможно добавить актиность, она пересекается с другими',
        OverlapTitle: 'Наложение',
        Pain: 'Боль',
        Palpitation: 'Сердцебиение',
        password: 'пароль',
        PhysicalLoad: 'Физическая нагрузка',
        PositionalChanges: 'Изменения положения',
        Positive: 'Позитивная',
        Postponed: 'Отложено',
        Press: 'Жим',
        Pressure: 'Давление',
        Problems: 'Проблемы',
        PsychoemotionalTest: 'Психоэмоциональные пробы',
        Register: 'Зарегистрироваться',
        ReliefOfAttack: 'Купирование приступа',
        RemindLater: 'Напомнить позже',
        RetrosternalPain: 'Боль за грудиной',
        Running: 'Бег',
        Save: 'Сохранить',
        Saved: 'Сохранено',
        September: 'Сентября',
        Service: 'Сервис',
        Settings: 'Настройки',
        Sex: 'Секс',
        Shower: 'Душ',
        Sleep: 'Сон',
        Smoking: 'Курение',
        Stairs: 'Лестница',
        Start: 'Начать',
        Steps: 'Шаги',
        StoragePermissions: 'Разрешение на хранение данных',
        StoragePermissionsMessage:
            'Cardio Journal нужен доступ к внутреннему хранилищу',
        Straining: 'Натуживание',
        Stupefaction: 'Помрачнение',
        Syncope: 'Обморок',
        Tachypnea: 'Учащённое дыхание',
        TakePhoto: 'Сделать фото',
        TakingMedicine: 'Лекарства',
        Tasks: 'Задания',
        Terminate: 'Прервать',
        TerminationExerciseQuestion:
            'Вы действительно хотите прервать занятие? Это необратимое действие',
        Tests: 'Пробы',
        Time: 'Время',
        Today: 'Сегодня',
        Toilet: 'Tуалет',
        Tomorrow: 'Завтра',
        Undefined: 'Без названия',
        username: 'имя пользователя',
        Version: 'Версия',
        VerticalPositionCalibration: 'Калибровка вертикальной позиции',
        VisionDisturbances: 'Нарушения зрения',
        Walking: 'Тест с 6-мин. ходьбой',
        Weakness: 'Слабость',
        WrongPassword: 'Неправильный логин или пароль',
        Yesterday: 'Вчера',
        YouClimbed: 'Вы поднялись на',
        YouWalked: 'Вы прошли',
        by: 'на',
        Cycling: 'Велотренажёр',
        Elliptical: 'Эллиптический',
        StairStepper: 'Лестничный',
        Joy: 'Радость',
        Sadness: 'Грусть',
        Anger: 'Гнев',
        Fear: 'Страх',
        Excitement: 'Волнение',
        Anxiety: 'Тревога',
        WeightLifting: 'Подъём тяжестей',
        PhysicalLabor: 'Физическая работа',
        Before: 'До',
        After: 'После',
        BloodPressure: 'Давление',
        NotFilledUp: 'Не заполнено',
        Straight: 'Прямо',
        LeaningForward: 'Нагнувшись вперёд',
        LeaningToTheLeft: 'Нагнувшись влево',
    },
})
