import LocalizedStrings from 'react-native-localization'

export const strings = new LocalizedStrings({
    'en-US': {
        AppTitle: 'Cardio Journal',
        username: 'username',
        password: 'password',
        Login: 'Login',
        Journal: 'Journal',
        Home: 'Home',
        Tasks: 'Tasks',
        Tests: 'Tests',
        Emotions: 'Emotions',
        Problems: 'Problems',
        Pain: 'Pain',
        Activity: 'Activity',
        Positive: 'Positive',
        Meal: 'Meal',
        Orthostasis: 'Orthostasis',
        TakingMedicine: 'Taking medicine',
        Quarrel: 'Quarrel',
        Sex: 'Sex',
        Smoking: 'Smoking',
        Stairs: 'Stairs',
        Alcohol: 'Alcohol',
        Walking: 'Walking',
        Sleep: 'Sleep',
        Yesterday: 'Yesterday',
        Today: 'Today',
        Tomorrow: 'Tomorrow',
        at: 'at',
        January: 'January',
        February: 'February',
        March: 'March',
        April: 'April',
        May: 'May',
        June: 'June',
        July: 'July',
        August: 'August',
        September: 'September',
        October: 'October',
        November: 'November',
        December: 'December',
        Gym: 'Gym',
        Toilet: 'Toilet',
        Shower: 'Shower',
        ReliefOfAttack: 'Relief of attack',
        CourseTherapy: 'Course therapy',
        Pain: 'Chest Pain',
        Headache: 'Anginous pain',
        RetrosternalPain: 'Retrosternal pain',
        HeartAreaPain: 'Heart area pain',
        Palpitation: 'Palpitation',
        Arrhythmia: 'Arrhythmia',
        Complaints: 'Disturbance of respiration',
        Dyspnea: 'Dyspnea',
        Tachypnea: 'Tachypnea',
        Weakness: 'Weakness',
        Faint: 'Faint',
        Stupefaction: 'Stupefaction',
        Nausea: 'Nausea',
        VisionDisturbances: 'Vision disturbances',
        Fatigue: 'Fatigue',
        Negative: 'Negative',
        PositionalChanges: 'Positional changes',
        Press: 'Press',
        Straining: 'Straining',
        MedicineTest: 'Medicine Test',
        PhysicalLoad: 'Physical activity',
        Comment: 'Comment',
        Save: 'Save',
        Logout: 'Logout',
        Terminate: 'Terminate',
        Start: 'Start',
        Steps: 'Steps',
        Distance: 'Distance',
        Cancel: 'Cancel',
        TerminationExerciseQuestion:
            "Do you really want to terminate the exercise? It can't be undone",
        Pressure: 'Pressure',
        mmHg: 'mmHg',
        notifText: `Time to complete the exercise. Tap here to start!`,
        minute: 'minute',
        minutes: 'minutes',
        hour: 'hour',
        hours: 'hours',
        Meters: 'Meters',
        RemindLater: 'Remind later',
        ExerciseFinish: 'Exercise finish',
        ExerciseFinishText: 'Good job! You completed the exercise!',
        HowDoYouFeelAfterThis: 'How do you feel after this?',
        Good: 'Good',
        Normal: 'Normal',
        Bad: 'Bad',
        Calibrating: 'Calibrating',
        HaveAGoodSleep: 'Have a good Sleep',
        ActivityEdit: 'Activity Edit',
        OverlapTitle: 'Overlap',
        OverlapMsg:
            "Can't add the activity, it's overlapping with exercises or Sleep",
        Saved: 'Saved',
        Alarm: 'Alarm',
        Locating: 'Looking for location!',
        FoundLocation: 'Location found!',
        FromStart: 'From start',
        FromEnd: 'From end',
        NotFilled: 'Not filled',
        Drug: 'Pill',
        CantGoBack: "Can't go back, you need to finish exercise first",
        Alert: 'Alert',
        Error: 'Error',
        NoConn: 'No Connection',
        CantConnect: "Can't connect to the server",
        Postponed: 'Postponed',
        Running: 'Running',
        Bicycling: 'Bicycling',
        GymWalking: 'Walking',
        ErrQR: 'Error readying QR code',
        CamPermDenied: 'Camera permission denied',
        AtivityStats: 'Activity statistics',
        NotSelected: 'Not selected',
        and: 'and',
        DeviceInstall: 'Device installation',
        DeviceId: 'Device id',
        YouClimbed: 'You climbed',
        YouWalked: 'You walked',
        DeviceInstalled: 'Device installed',
        NoPhoto: 'No Photo',
        Register: 'Register',
        idinv: 'Investigation ID',
        EditProfile: 'Edit profile',
        Settings: 'Settings',
        CameraPermissions: 'Camera Permissions',
        MicrophonePermissions: 'Microphone Permissions',
        StoragePermissions: 'Storage Permissions',
        LocationPermissions: 'Location Permissions',
        Ok: 'Ok',
        AskMeLater: 'Ask me later',
        CameraPermissionsMessage: 'Cardio Journal needs access to your camera',
        LocationPermissionsMessage:
            'Cardio Journal needs access to your location',
        MicrophonePermissionsMessage:
            'Cardio Journal needs access to your microphone',
        StoragePermissionsMessage:
            'Cardio Journal needs access to your internal storage',
        WrongPassword: 'Wrong username or password',
        PhysicalLoad: 'Psysical load',
        Other: 'Other',
        EmotionalStress: 'EmotionalStress',
        Pain: 'Pain',
        Complaints: 'Complaints',
        Service: 'Service',
        Positive: 'Positive',
        Negative: 'Negative',
        Headache: 'Headache',
        Syncope: 'Syncope',
        CuffFix: 'Cuff fix',
        Gym: 'Gym',
        OtherLoad: 'Other load',
        OtherActivity: 'Other activity',
        OtherEmotions: 'Other emotions',
        OtherPain: 'Other pain',
        OtherComplaints: 'Other complaints',
        OtherWeakness: 'Other weakness',
        ElectrodeReplacement: 'Electrode replacement',
        VerticalPositionCalibration: 'Vertical Position Calibration',
        PsychoemotionalTest: 'Psychoemotional test',
        Time: 'Time',
        Duration: 'Duration',
        TakePhoto: 'Take a photo',
        Undefined: 'Undefined',
        GymType: 'Exercise machine type',
        Calories: 'Calories',
    },
    es: {
        AppTitle: 'Diario de Cardio',
        username: 'nombre de usuario',
        password: 'contraseña',
        Login: 'Entrar',
        Journal: 'Diario',
        Home: 'Principal',
        Tasks: 'Tareas',
        Tests: 'Pruebas',
        Emotions: 'Emociones',
        Problems: 'Problemas',
        Pain: 'Dolor',
        Activity: 'Actividad',
        Positive: 'Positiva',
        Meal: 'Comida',
        Orthostasis: 'Ortostasis',
        TakingMedicine: 'Pastillas',
        Quarrel: 'Pelea',
        Sex: 'Sexo',
        Smoking: 'Fumar',
        Stairs: 'Escalera',
        Alcohol: 'Alcohol',
        Walking: 'Caminar',
        Sleep: 'Dormir',
        Yesterday: 'Ayer',
        Today: 'Hoy',
        Tomorrow: 'Mañana',
        at: 'a',
        January: 'Jenero',
        February: 'Febrero',
        March: 'Marso',
        April: 'Abril',
        May: 'Mayo',
        June: 'Junio',
        July: 'Julio',
        August: 'Agosto',
        September: 'Septiembre',
        October: 'Octubre',
        November: 'Noviembre',
        December: 'Diciembre',
        Gym: 'Ejercicio',
        Toilet: 'Baño',
        Shower: 'Ducha',
        ReliefOfAttack: 'Alivio del ataque',
        CourseTherapy: 'Curso de terapia',
        Pain: 'Dolor de pecho',
        Headache: 'Dolor anginoso',
        RetrosternalPain: 'Dolor retrosternal',
        HeartAreaPain: 'Dolor en área del corazón',
        Palpitation: 'Palpitación',
        Arrhythmia: 'Arritmia',
        Complaints: 'Alteración de la respiración',
        Dyspnea: 'Disnea',
        Tachypnea: 'Taquipnea',
        Weakness: 'Debilidad',
        Faint: 'Débil',
        Stupefaction: 'Estupefacción',
        Nausea: 'Náusea',
        VisionDisturbances: 'Trastornos de la visión',
        Fatigue: 'Fatiga',
        Negative: 'Negativa',
        PositionalChanges: 'Cambios posicionales',
        Press: 'Press',
        Straining: 'Tirante',
        MedicineTest: 'Prueba de medicina',
        PhysicalLoad: 'Actividad física',
        Comment: 'Comentario',
        Save: 'Salvar',
        Logout: 'Cerrar',
        Terminate: 'Terninar',
        Start: 'Comenzar',
        Steps: 'Pasas',
        Distance: 'Distancia',
        Cancel: 'Cancelar',
        TerminationExerciseQuestion:
            '¿Realmente quieres terminar el ejercicio? No se puede deshacer',
        Pressure: 'Presión',
        mmHg: 'mmHg',
        notifText: `Tiempo para completar el ejercicio. Toque aquí para comenzar!`,
        minute: 'minuto',
        minutes: 'minutos',
        hour: 'hora',
        hours: 'horas',
        Meters: 'Metros',
        RemindLater: 'Recordar mas tarde',
        ExerciseFinish: 'Ejercicio finalizado',
        ExerciseFinishText: '¡Buen trabajo! ¡Has completado el ejercicio!',
        HowDoYouFeelAfterThis: '¿Cómo te sientes después de esto?',
        Good: 'Bien',
        Normal: 'Normal',
        Bad: 'Mal',
        Calibrating: 'Calibración',
        HaveAGoodSleep: 'Tener un buen descanso',
        ActivityEdit: 'edición de la actividad',
        OverlapTitle: 'Superposición',
        OverlapMsg:
            'No es possible agregar la actividad, se superpone con ejercicios o descanso.',
        Saved: 'Salvado',
        Alarm: 'Problema',
        Locating: '¡Buscando ubicación!',
        FoundLocation: '¡Ubicación encontrada!',
        FromStart: 'Del principio',
        FromEnd: 'Del final',
        NotFilled: 'No llenado',
        Drug: 'Postilla',
        CantGoBack: 'No puedes volver, necesitas terminar el ejercicio primero',
        Alert: 'Alerta',
        Error: 'Error',
        NoConn: 'Sin conexión',
        CantConnect: 'No se puede conectar al servidor',
        Postponed: 'Pospuesto',
        Running: 'Corriendo',
        Bicycling: 'Montar en bicicleta',
        GymWalking: 'Caminar normal',
        ErrQR: 'Error al preparar el código QR',
        CamPermDenied: 'Permiso de la cámara denegado',
        AtivityStats: 'Estadísticas de actividad',
        NotSelected: 'No seleccionado',
        and: 'y',
        DeviceInstall: 'Installación del despositivo',
        DeviceId: 'Identificación del dispositivo',
        YouClimbed: 'Usted subió',
        YouWalked: 'Usted caminó',
        DeviceInstalled: 'Dispositivo instalado',
        NoPhoto: 'No hay foto',
        Register: 'Registrarse',
        idinv: 'Identificación de investigación',
        EditProfile: 'Editar perfil',
        Settings: 'Configuraciones',
        CameraPermissions: 'Permisos de сámera',
        MicrophonePermissions: 'Permisos de micrófono',
        StoragePermissions: 'Permisos de almacenamiento',
        LocationPermissions: 'Permisos de ubicación',
        Ok: 'Ok',
        AskMeLater: 'Pregúntame luego',
        CameraPermissionsMessage: 'Cardio Journal necesita acceso a tu cámara',
        LocationPermissionsMessage:
            'Cardio Journal necesita acceso a tu ubicación',
        MicrophonePermissionsMessage:
            'Cardio Journal necesita acceso a tu micrófono',
        StoragePermissionsMessage:
            'Cardio Journal necesita acceso a tu almacenamiento',
        WrongPassword: 'Nombre de usuario o contraseña incorrectos',
        PhysicalLoad: 'Carga fisica',
        Other: 'Otra',
        EmotionalStress: 'Estrés emocional',
        Pain: 'Dolor',
        Complaints: 'Quejas',
        Service: 'Servicio',
        Positive: 'Positiva',
        Negative: 'Negativa',
        Headache: 'Dolor de cabeza',
        Syncope: 'Síncope',
        CuffFix: 'Brazalete fijar',
        Gym: 'Gimnasio',
        OtherLoad: 'Otra carga',
        OtherActivity: 'Otra actividad',
        OtherEmotions: 'Otras emociones ',
        OtherPain: 'Otro dolor',
        OtherComplaints: 'Otras quejas',
        OtherWeakness: 'Otra debilidad',
        ElectrodeReplacement: 'Reemplazo de electrodos',
        VerticalPositionCalibration: 'Calibración de posición vertical',
        PsychoemotionalTest: 'Prueba psicoemocional',
        Time: 'Tiempo',
        Duration: 'Duración',
        TakePhoto: 'Tomar un foto',
        Undefined: 'Indefinida',
        GymType: 'Tipo de máquina de ejercicio',
        Calories: 'Calorías',
    },
    ru: {
        AppTitle: 'Кардио журнал',
        username: 'имя пользователя',
        password: 'пароль',
        Login: 'Войти',
        Journal: 'Дневник',
        Home: 'Дом',
        Tasks: 'Задания',
        Tests: 'Тесты',
        Emotions: 'Эмоции',
        Problems: 'Проблемы',
        Pain: 'Боль',
        Activity: 'Активность',
        Positive: 'Позитивная',
        Meal: 'Еда',
        Orthostasis: 'Ортостаз',
        TakingMedicine: 'Приём препарата',
        Quarrel: 'Ссора',
        Sex: 'Секс',
        Smoking: 'Курение',
        Stairs: 'Лестница',
        Alcohol: 'Алкоголь',
        Walking: 'Ходьба',
        Sleep: 'Сон',
        Yesterday: 'Вчера',
        Today: 'Сегодня',
        Tomorrow: 'Завтра',
        at: 'в',
        January: 'Января',
        February: 'Февраля',
        March: 'Марта',
        April: 'Апреля',
        May: 'Мая',
        June: 'Июня',
        July: 'Июля',
        August: 'Августа',
        September: 'Сентября',
        October: 'Октября',
        November: 'Ноября',
        December: 'Декабря',
        Gym: 'Тренажёр',
        Toilet: 'Tуалет',
        Shower: 'Душ',
        ReliefOfAttack: 'Купирование приступа',
        CourseTherapy: 'Курсовая терапия',
        Pain: 'Боль в грудной клетке',
        Headache: 'Ангинальная боль',
        RetrosternalPain: 'Боль за грудиной',
        HeartAreaPain: 'Боль в области сердца',
        Palpitation: 'Пульсация',
        Arrhythmia: 'Аритмия',
        Complaints: 'Нарушения дыхания',
        Dyspnea: 'Одышка',
        Tachypnea: 'Учащённое дышание',
        Weakness: 'Слабость',
        Faint: 'Дурнота',
        Stupefaction: 'Помрачнение',
        Nausea: 'Тошнота',
        VisionDisturbances: 'Нарушения зрения',
        Fatigue: 'Усталость',
        Negative: 'Негативная',
        PositionalChanges: 'Изменения положения',
        Press: 'Пресс',
        Straining: 'Натуживание',
        MedicineTest: 'Тестируемый препарат',
        PhysicalLoad: 'Физическая автивность',
        Comment: 'Комментарий',
        Save: 'Сохранить',
        Logout: 'Выйти',
        Terminate: 'Прервать',
        Start: 'Начать',
        Steps: 'Шаги',
        Distance: 'Расстояние',
        Finish: 'Завершить',
        Cancel: 'Отменить',
        TerminationExerciseQuestion:
            'Вы действительно хотите прервать занятие? Это необратимое действие',
        Pressure: 'Давление',
        mmHg: 'мм рт.ст.',
        notifText: `Время выполнить задание. Нажмите, чтобы начать!`,
        minute: 'минута',
        minutes: 'минут',
        hour: 'час',
        hours: 'часов',
        Meters: 'Метров',
        RemindLater: 'Напомнить позже',
        ExerciseFinish: 'Завершение затяния',
        ExerciseFinishText: 'Поздравляем, вы справились с занятием!',
        HowDoYouFeelAfterThis: 'Как вы себя чувствуете после этого?',
        Good: 'Хорошо',
        Normal: 'Нормально',
        Bad: 'Плохо',
        Calibrating: 'Калибровка',
        HaveAGoodSleep: 'Приятного отдыха',
        ActivityEdit: 'Редактирование активности',
        OverlapTitle: 'Наложение',
        OverlapMsg:
            'Невозможно добавить актиность, она пересекается с другими.',
        Saved: 'Сохранено',
        Alarm: 'Тревога',
        Locating: 'Поиск местоположения!',
        FoundLocation: 'Местоположение найдено!',
        FromStart: 'Время начала',
        FromEnd: 'Время конца',
        NotFilled: 'Не заполнено',
        Drug: 'Препарат',
        CantGoBack: 'Нельзя вернуться, сначала закончите занятие',
        Alert: 'Внимание',
        Error: 'Ошибка',
        NoConn: 'Нет соединения',
        CantConnect: 'Невозможно соединиться с сервером',
        Postponed: 'Отложено',
        Running: 'Бег',
        Bicycling: 'Велосипед',
        GymWalking: 'Ходьба',
        ErrQR: 'Не удаётся прочесть QR код',
        CamPermDenied: 'Отказано в использовании камеры',
        AtivityStats: 'Статистика активности',
        NotSelected: 'Не выбрано',
        and: 'и',
        DeviceInstall: 'Установка прибора',
        DeviceId: 'Номер устройства',
        YouClimbed: 'Вы поднялись на',
        YouWalked: 'Вы прошли',
        DeviceInstalled: 'Устройство установлено',
        NoPhoto: 'Нет фото',
        Register: 'Зарегистрироваться',
        idinv: 'Номер обследования',
        EditProfile: 'Редактировать профиль',
        Settings: 'Настройки',
        CameraPermissions: 'Разрешение на использование камеры',
        MicrophonePermissions: 'Разрешение на использование микрофона',
        StoragePermissions: 'Разрешение на хранение данных',
        LocationPermissions: 'Разрешение на использование геолокации',
        Ok: 'Ok',
        AskMeLater: 'Спросить позже',
        CameraPermissionsMessage: 'Cardio Journal нужен доступ к камере',
        LocationPermissionsMessage: 'Cardio Journal нужен доступ к геолокации',
        MicrophonePermissionsMessage: 'Cardio Journal нужен доступ к микрофону',
        StoragePermissionsMessage:
            'Cardio Journal нужен доступ к внутреннему хранилищу',
        WrongPassword: 'Неправильный логин или пароль',
        PhysicalLoad: 'Физическая нагрузка',
        Other: 'Другое',
        EmotionalStress: 'Эмоциональная нагрузка',
        Pain: 'Боль',
        Complaints: 'Жалобы',
        Service: 'Сервис',
        Positive: 'Позитивная',
        Negative: 'Негативная',
        Headache: 'Головная боль',
        Syncope: 'Обморок',
        CuffFix: 'Поправка манжета',
        Gym: 'Тренажёр',
        OtherLoad: 'Другая нагрузка',
        OtherActivity: 'Другая активность',
        OtherEmotions: 'Другие эмоции',
        OtherPain: 'Другая боль',
        OtherComplaints: 'Другие жалобы',
        OtherWeakness: 'Другая слабость',
        ElectrodeReplacement: 'Замена электрода',
        VerticalPositionCalibration: 'Калибровка вертикальной позиции',
        Press: 'Жим',
        Straining: 'Натуживание',
        PsychoemotionalTest: 'Психоэмоциональные пробы',
        Time: 'Время',
        Duration: 'Длительность',
        TakePhoto: 'Сделать фото',
        Undefined: 'Без названия',
        GymType: 'Тип тренажёра',
        Calories: 'Калории',
    },
})
