import LocalizedStrings from 'react-native-localization'

export const strings = new LocalizedStrings({
    'en-US': {
        AppTitle: 'Cardio Journal',
        email: 'email',
        password: 'password',
        Login: 'Login',
        Journal: 'Journal',
        Home: 'Home',
        Tasks: 'Tasks',
        Tests: 'Tests',
        Intake: 'Intake',
        Emotions: 'Emotions',
        Problems: 'Problems',
        Pain: 'Pain',
        Activity: 'Activity',
        Anxiety: 'Anxiety',
        Excitement: 'Excitement',
        Happy: 'Happy',
        Meal: 'Meal',
        Orthostasis: 'Orthostasis',
        TakingMedicine: 'Taking medicine',
        Quarrel: 'Quarrel',
        Sex: 'Sex',
        Smoking: 'Smoking',
        Stairs: 'Stairs',
        Alcohol: 'Alcohol',
        Walking: 'Walking',
        Sleep: 'Sleep',
        Rest: 'Rest',
        Yesterday: 'Yesterday',
        Today: 'Today',
        Tomorrow: 'Tomorrow',
        at: 'at',
        January: 'January',
        February: 'February',
        March: 'March',
        April: 'April',
        May: 'May',
        June: 'June',
        July: 'July',
        August: 'August',
        September: 'September',
        October: 'October',
        November: 'November',
        December: 'December',
        Rest: 'Rest',
        Workout: 'Workout',
        Toilet: 'Toilet',
        Sauna: 'Sauna',
        PhysicalWork: 'Physical work',
        Shower: 'Shower',
        IntellectualWork: 'Intellectual work',
        Gambling: 'Gambling',
        Viewing: 'Viewing',
        Reading: 'Reading',
        Psychotherapy: 'Psychotherapy',
        Relaxation: 'Relaxation',
        Influence: 'Influence',
        Massage: 'Massage',
        Physiotherapy: 'Physiotherapy',
        Sunbathe: 'Sunbathe',
        ReliefOfAttack: 'Relief of attack',
        CourseTherapy: 'Course therapy',
        ChestPain: 'Chest Pain',
        AnginousPain: 'Anginous pain',
        RetrosternalPain: 'Retrosternal pain',
        HeartAreaPain: 'Heart area pain',
        CardiacRhythmDisturbance: 'Cardiac rhythm disturbance',
        Palpitation: 'Palpitation',
        Arrhythmia: 'Arrhythmia',
        DisturbanceOfRespiration: 'Disturbance of respiration',
        Dyspnea: 'Dyspnea',
        Tachypnea: 'Tachypnea',
        Weakness: 'Weakness',
        Faint: 'Faint',
        Stupefaction: 'Stupefaction',
        Nausea: 'Nausea',
        VisionDisturbances: 'Vision disturbances',
        Fatigue: 'Fatigue',
        Joy: 'Joy',
        Sadness: 'Sadness',
        Anger: 'Anger',
        Fear: 'Fear',
        PositionalChanges: 'Positional changes',
        Press: 'Press',
        Straining: 'Straining',
        OneTimeTakingOfMedicine: 'One time taking of medicine',
        PsychologicalActivity: 'Psychological activity',
        PhysicalActivity: 'Physical activity',
        Comment: 'Comment',
        Save: 'Save',
        Logout: 'Logout',
        Terminate: 'Terminate',
        Start: 'Start',
        Steps: 'Steps',
        Distance: 'Distance',
        Cancel: 'Cancel',
        TerminationExerciseQuestion:
            "Do you really want to terminate the exercise? It can't be undone",
        Pressure: 'Pressure',
        mmHg: 'mmHg',
        notifText: `Time to complete the exercise. Tap here to start!`,
        minute: 'minute',
        minutes: 'minutes',
        hour: 'hour',
        hours: 'hours',
        Meters: 'Meters',
        RemindLater: 'Remind later',
        ExerciseFinish: 'Exercise finish',
        ExerciseFinishText: 'Good job! You completed the exercise!',
        HowDoYouFeelAfterThis: 'How do you feel after this?',
        Good: 'Good',
        Normal: 'Normal',
        Bad: 'Bad',
        Calibrating: 'Calibrating',
        HaveAGoodRest: 'Have a good rest',
        ActivityEdit: 'Activity Edit',
        OverlapTitle: 'Overlap',
        OverlapMsg:
            "Can't add the activity, it's overlapping with exercises or rest",
        Saved: 'Saved',
        Trouble: 'Trouble',
        Locating: 'Looking for location!',
        FoundLocation: 'Location found!',
        FromStart: 'From start',
        FromEnd: 'From end',
        NotFilled: 'Not filled',
        Drug: 'Pill',
        CantGoBack: "Can't go back, you need to finish exercise first",
        Alert: 'Alert',
        Error: 'Error',
        NoConn: 'No Connection',
        CantConnect: "Can't connect to the server",
        Postponed: 'Postponed',
        Running: 'Running',
        Bicycling: 'Bicycling',
        WorkoutWalking: 'Normal walking',
        ErrQR: 'Error readying QR code',
        CamPermDenied: 'Camera permission denied',
        AtivityStats: 'Activity statistics',
        NotSelected: 'Not selected',
        and: 'and',
        DeviceInstall: 'Device installation',
        DeviceId: 'Device id',
        YouClimbed: 'You climbed',
        YouWalked: 'You walked',
        DeviceInstalled: 'Device installed',
        NoPhoto: 'No Photo',
        Register: 'Register',
        idinv: 'Investigation ID',
        EditProfile: 'Edit profile',
        Settings: 'Settings',
    },
    es: {
        AppTitle: 'Diario de Cardio',
        email: 'email',
        password: 'contraseña',
        Login: 'Entrar',
        Journal: 'Diario',
        Home: 'Principal',
        Tasks: 'Tareas',
        Tests: 'Pruebas',
        Intake: 'Consumo',
        Emotions: 'Emociones',
        Problems: 'Problemas',
        Pain: 'Dolor',
        Activity: 'Actividad',
        Anxiety: 'Ansiedad',
        Excitement: 'Excitación',
        Happy: 'Feliz',
        Meal: 'Comida',
        Orthostasis: 'Ortostasis',
        TakingMedicine: 'Pastillas',
        Quarrel: 'Pelea',
        Sex: 'Sexo',
        Smoking: 'Fumar',
        Stairs: 'Escalera',
        Alcohol: 'Alcohol',
        Walking: 'Caminar',
        Sleep: 'Sleep',
        Rest: 'Descansar',
        Yesterday: 'Ayer',
        Today: 'Hoy',
        Tomorrow: 'Mañana',
        at: 'a',
        January: 'Jenero',
        February: 'Febrero',
        March: 'Marso',
        April: 'Abril',
        May: 'Mayo',
        June: 'Junio',
        July: 'Julio',
        August: 'Agosto',
        September: 'Septiembre',
        October: 'Octubre',
        November: 'Noviembre',
        December: 'Diciembre',
        Rest: 'Descanso',
        Workout: 'Ejercicio',
        Toilet: 'Baño',
        Sauna: 'Sauna',
        PhysicalWork: 'Trabajo físico',
        Shower: 'Ducha',
        IntellectualWork: 'Trabajo intelectual',
        Gambling: 'Juego',
        Viewing: 'Viendo',
        Reading: 'Leyendo',
        Psychotherapy: 'Psicoterapia',
        Relaxation: 'Relajación',
        Influence: 'Influencia',
        Massage: 'Masaje',
        Physiotherapy: 'Fisioterapia',
        Sunbathe: 'Tomar el sol',
        ReliefOfAttack: 'Alivio del ataque',
        CourseTherapy: 'Curso de terapia',
        ChestPain: 'Dolor de pecho',
        AnginousPain: 'Dolor anginoso',
        RetrosternalPain: 'Dolor retrosternal',
        HeartAreaPain: 'Dolor en área del corazón',
        CardiacRhythmDisturbance: 'Alteración del ritmo cardíaco',
        Palpitation: 'Palpitación',
        Arrhythmia: 'Arritmia',
        DisturbanceOfRespiration: 'Alteración de la respiración',
        Dyspnea: 'Disnea',
        Tachypnea: 'Taquipnea',
        Weakness: 'Debilidad',
        Faint: 'Débil',
        Stupefaction: 'Estupefacción',
        Nausea: 'Náusea',
        VisionDisturbances: 'Trastornos de la visión',
        Fatigue: 'Fatiga',
        Joy: 'Alegría',
        Sadness: 'Tristeza',
        Anger: 'Anger',
        Fear: 'Temor',
        PositionalChanges: 'Cambios posicionales',
        Press: 'Press',
        Straining: 'Tirante',
        OneTimeTakingOfMedicine: 'Toma de medicina una vez',
        PsychologicalActivity: 'Actividad psicologica',
        PhysicalActivity: 'Actividad física',
        Comment: 'Comentario',
        Save: 'Salvar',
        Logout: 'Cerrar',
        Terminate: 'Terninar',
        Start: 'Comenzar',
        Steps: 'Pasas',
        Distance: 'Distancia',
        Cancel: 'Cancelar',
        TerminationExerciseQuestion:
            '¿Realmente quieres terminar el ejercicio? No se puede deshacer',
        Pressure: 'Presión',
        mmHg: 'mmHg',
        notifText: `Tiempo para completar el ejercicio. Toque aquí para comenzar!`,
        minute: 'minuto',
        minutes: 'minutos',
        hour: 'hora',
        hours: 'horas',
        Meters: 'Metros',
        RemindLater: 'Recordar mas tarde',
        ExerciseFinish: 'Ejercicio finalizado',
        ExerciseFinishText: '¡Buen trabajo! ¡Has completado el ejercicio!',
        HowDoYouFeelAfterThis: '¿Cómo te sientes después de esto?',
        Good: 'Bien',
        Normal: 'Normal',
        Bad: 'Mal',
        Calibrating: 'Calibración',
        HaveAGoodRest: 'Tener un buen descanso',
        ActivityEdit: 'edición de la actividad',
        OverlapTitle: 'Superposición',
        OverlapMsg:
            'No es possible agregar la actividad, se superpone con ejercicios o descanso.',
        Saved: 'Salvado',
        Trouble: 'Problema',
        Locating: '¡Buscando ubicación!',
        FoundLocation: '¡Ubicación encontrada!',
        FromStart: 'Del principio',
        FromEnd: 'Del final',
        NotFilled: 'No llenado',
        Drug: 'Postilla',
        CantGoBack: 'No puedes volver, necesitas terminar el ejercicio primero',
        Alert: 'Alerta',
        Error: 'Error',
        NoConn: 'Sin conexión',
        CantConnect: 'No se puede conectar al servidor',
        Postponed: 'Pospuesto',
        Running: 'Corriendo',
        Bicycling: 'Montar en bicicleta',
        WorkoutWalking: 'Caminar normal',
        ErrQR: 'Error al preparar el código QR',
        CamPermDenied: 'Permiso de la cámara denegado',
        AtivityStats: 'Estadísticas de actividad',
        NotSelected: 'No seleccionado',
        and: 'y',
        DeviceInstall: 'Installación del despositivo',
        DeviceId: 'Identificación del dispositivo',
        YouClimbed: 'Usted subió',
        YouWalked: 'Usted caminó',
        DeviceInstalled: 'Dispositivo instalado',
        NoPhoto: 'No hay foto',
        Register: 'Registrarse',
        idinv: 'Identificación de investigación',
        EditProfile: 'Editar perfil',
        Settings: 'Configuraciones',
    },
    ru: {
        AppTitle: 'Кардио журнал',
        email: 'электронная почта',
        password: 'пароль',
        Login: 'Войти',
        Journal: 'Дневник',
        Home: 'Дом',
        Tasks: 'Задания',
        Tests: 'Тесты',
        Intake: 'Приём',
        Emotions: 'Эмоции',
        Problems: 'Проблемы',
        Pain: 'Боль',
        Activity: 'Активность',
        Anxiety: 'Беспокойство',
        Excitement: 'Возбуждение',
        Happy: 'Счастье',
        Meal: 'Еда',
        Orthostasis: 'Ортостаз',
        TakingMedicine: 'Приём препарата',
        Quarrel: 'Ссора',
        Sex: 'Секс',
        Smoking: 'Курение',
        Stairs: 'Лестница',
        Alcohol: 'Алкоголь',
        Walking: 'Ходьба',
        Sleep: 'Сон',
        Rest: 'Отдых',
        Yesterday: 'Вчера',
        Today: 'Сегодня',
        Tomorrow: 'Завтра',
        at: 'в',
        January: 'Января',
        February: 'Февраля',
        March: 'Марта',
        April: 'Апреля',
        May: 'Мая',
        June: 'Июня',
        July: 'Июля',
        August: 'Августа',
        September: 'Сентября',
        October: 'Октября',
        November: 'Ноября',
        December: 'Декабря',
        Rest: 'Покой',
        Workout: 'Упражнения',
        Toilet: 'Tуалет',
        Sauna: 'Сауна',
        PhysicalWork: 'Физическая работа',
        Shower: 'Душ',
        IntellectualWork: 'Интеллектуальная работа',
        Gambling: 'Азартные игры',
        Viewing: 'Просмотр',
        Reading: 'Чтение',
        Psychotherapy: 'Психотерапия',
        Relaxation: 'Отдых',
        Influence: 'Воздействие',
        Massage: 'Массаж',
        Physiotherapy: 'Физиотерапия',
        Sunbathe: 'Загар',
        ReliefOfAttack: 'Купирование приступа',
        CourseTherapy: 'Курсовая терапия',
        ChestPain: 'Боль в грудной клетке',
        AnginousPain: 'Ангинальная боль',
        RetrosternalPain: 'Боль за грудиной',
        HeartAreaPain: 'Боль в области сердца',
        CardiacRhythmDisturbance: 'Нарушения сердечного ритма',
        Palpitation: 'Пульсация',
        Arrhythmia: 'Аритмия',
        DisturbanceOfRespiration: 'Нарушения дыхания',
        Dyspnea: 'Одышка',
        Tachypnea: 'Учащённое дышание',
        Weakness: 'Слабость',
        Faint: 'Обморок',
        Stupefaction: 'Ступость',
        Nausea: 'Тошнота',
        VisionDisturbances: 'Нарушения зрения',
        Fatigue: 'Усталость',
        Joy: 'Радость',
        Sadness: 'Грусть',
        Anger: 'Злость',
        Fear: 'Страх',
        PositionalChanges: 'Изменения положения',
        Press: 'Пресс',
        Straining: 'Натуживание',
        OneTimeTakingOfMedicine: 'Разовый приём препарата',
        PsychologicalActivity: 'Психологическая активность',
        PhysicalActivity: 'Физическая автивность',
        Comment: 'Комментарий',
        Save: 'Сохранить',
        Logout: 'Выйти',
        Terminate: 'Прервать',
        Start: 'Начать',
        Steps: 'Шаги',
        Distance: 'Расстояние',
        Finish: 'Завершить',
        Cancel: 'Отменить',
        TerminationExerciseQuestion:
            'Вы действительно хотите прервать занятие? Это необратимое действие',
        Pressure: 'Давление',
        mmHg: 'мм рт.ст.',
        notifText: `Время выполнить задание. Нажмите, чтобы начать!`,
        minute: 'минута',
        minutes: 'минут',
        hour: 'час',
        hours: 'часов',
        Meters: 'Метров',
        RemindLater: 'Напомнить позже',
        ExerciseFinish: 'Завершение затяния',
        ExerciseFinishText: 'Поздравляем, вы справились с занятием!',
        HowDoYouFeelAfterThis: 'Как вы себя чувствуете после этого?',
        Good: 'Хорошо',
        Normal: 'Нормально',
        Bad: 'Плохо',
        Calibrating: 'Калибровка',
        HaveAGoodRest: 'Приятного отдыха',
        ActivityEdit: 'Редактирование активности',
        OverlapTitle: 'Наложение',
        OverlapMsg:
            'Невозможно добавить актиность, она пересекается с другими.',
        Saved: 'Сохранено',
        Trouble: 'Тревога',
        Locating: 'Поиск местоположения!',
        FoundLocation: 'Местоположение найдено!',
        FromStart: 'Время начала',
        FromEnd: 'Время конца',
        NotFilled: 'Не заполнено',
        Drug: 'Препарат',
        CantGoBack: 'Нельзя вернуться, сначала закончите занятие',
        Alert: 'Внимание',
        Error: 'Ошибка',
        NoConn: 'Нет соединения',
        CantConnect: 'Невозможно соединиться с сервером',
        Postponed: 'Отложено',
        Running: 'Бег',
        Bicycling: 'Езда на велосипеде',
        WorkoutWalking: 'Обычная ходьба',
        ErrQR: 'Не удаётся прочесть QR код',
        CamPermDenied: 'Отказано в использовании камеры',
        AtivityStats: 'Статистика активности',
        NotSelected: 'Не выбрано',
        and: 'и',
        DeviceInstall: 'Установка прибора',
        DeviceId: 'Номер устройства',
        YouClimbed: 'Вы поднялись на',
        YouWalked: 'Вы прошли',
        DeviceInstalled: 'Устройство установлено',
        NoPhoto: 'Нет фото',
        Register: 'Зарегистрироваться',
        idinv: 'Номер обследования',
        EditProfile: 'Редактировать профиль',
        Settings: 'Настройки',
    },
})
