interface IDuration {
    [key: string]: { duration: number; offset: number }
}

export const defaultDurations: IDuration = {
    Sleep: { duration: 28800, offset: 28800 },
    CuffFix: { duration: 60, offset: 60 },
    ElectrodeReplacement: { duration: 60, offset: 60 },
    Running: { duration: 600, offset: 0 },
    Bicycling: { duration: 600, offset: 0 },
    Walking: { duration: 600, offset: 0 },
    Syncope: { duration: 300, offset: 300 },
    Trainer: { duration: 600, offset: 0 },
    Sex: { duration: 600, offset: 0 },
    Toilet: { duration: 180, offset: 0 },
    Shower: { duration: 600, offset: 0 },
    Alarm: { duration: 0, offset: 0 },
    Meal: { duration: 600, offset: 0 },
    Alcohol: { duration: 600, offset: 0 },
    Smoking: { duration: 120, offset: 0 },
    ReliefOfAttack: { duration: 0, offset: 0 },
    CourseTherapy: { duration: 0, offset: 0 },
    Headache: { duration: 600, offset: 300 },
    RetrosternalPain: { duration: 600, offset: 300 },
    HeartAreaPain: { duration: 600, offset: 300 },
    Palpitation: { duration: 600, offset: 300 },
    Arrhythmia: { duration: 600, offset: 300 },
    Dyspnea: { duration: 600, offset: 300 },
    Tachypnea: { duration: 600, offset: 300 },
    Stupefaction: { duration: 600, offset: 300 },
    Nausea: { duration: 600, offset: 300 },
    VisionDisturbances: { duration: 600, offset: 300 },
    Fatigue: { duration: 600, offset: 300 },
    PositiveEmotions: { duration: 600, offset: 0 },
    NegativeEmotions: { duration: 600, offset: 0 },
    ActiveOrthostasis: { duration: 60, offset: 0 },
    PositionalChanges: { duration: 60, offset: 0 },
    Press: { duration: 60, offset: 0 },
    Straining: { duration: 60, offset: 0 },
    MedicineTest: { duration: 0, offset: 0 },
    DeviceInstall: { duration: 0, offset: 0 },
    OtherLoad: { duration: 600, offset: 0 },
    OtherActivity: { duration: 600, offset: 0 },
    OtherEmotions: { duration: 600, offset: 0 },
    OtherPain: { duration: 600, offset: 300 },
    OtherComplaints: { duration: 600, offset: 300 },
    OtherWeakness: { duration: 600, offset: 300 },
    VerticalPositionCalibration: { duration: 60, offset: 60 },
    PsychoemotionalTest: { duration: 600, offset: 0 },
    DeepBreathing: { duration: 60, offset: 0 },
    Workout: { duration: 600, offset: 0 },
}
