// Activity
export const ADD_ACTIVITY = 'ADD_ACTIVITY'
export const REPLACE_ACTIVITIES = 'REPLACE_ACTIVITIES'
export const UPDATE_ACTIVITIES = 'UPDATE_ACTIVITIES'
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY'
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY'
export const ACTIVITY_SET_ID = 'ACTIVITY_SET_ID'
export const ACTIVITY_SYNCED = 'ACTIVITY_SYNCED'
export const ACTIVITY_DELETED = 'ACTIVITY_DELETED'
export const ACTIVITY_SYNC_FAILED = 'ACTIVITY_SYNC_FAILED'
export const ACTIVITY_FETCH_FAILED = 'ACTIVITY_FETCH_FAILED'

// settings
export const SET_IDINV_FILTER = 'SET_IDINV_FILTER'
export const SET_NOTIFICATION_DELAY = 'SET_NOTIFICATION_DELAY'
export const LOAD_SETTINGS = 'LOAD_SETTINGS'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'

//Tasks
export const REPLACE_TASKS = 'REPLACE_TASKS'
export const TASK_COMPLETE = 'TASK_COMPLETE'
export const TASKS_FETCH_FAILED = 'TASKS_FETCH_FAILED'
export const TASK_SET_NOTIFICATIONS = 'TASK_SET_NOTIFICATIONS'
export const TASK_NOTIFICATIONS_FIRED = 'TASK_NOTIFICATIONS_FIRED'
export const TASK_DELAY_NOTIFICATION = 'TASK_DELAY_NOTIFICATION'
export const TASK_CANCEL_NOTIFICATION = 'TASK_CANCEL_NOTIFICATION'

// Tokens
export const TOKENS_RECEIVED = 'TOKENS_RECEIVED'
export const TOKENS_LOADED = 'TOKENS_LOADED'

// User
export const UPDATE_USER = 'UPDATE_USER'
export const IDENTITY_USER = 'IDENTITY_USER'
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED'
export const LOGOUT_USER = 'LOGOUT_USER'
