export const en = {
    Activity: 'Activity',
    ActivityEdit: 'Activity Edit',
    Alarm: 'Alarm',
    Alcohol: 'Alcohol',
    Alert: 'Alert',
    and: 'and',
    AppTitle: 'Cardio Journal',
    April: 'April',
    Arrhythmia: 'Arrhythmia',
    AskMeLater: 'Ask me later',
    at: 'at',
    AtivityStats: 'Activity statistics',
    August: 'August',
    Bad: 'Bad',
    Bicycling: 'Bicycling',
    Calibrating: 'Calibrating',
    Calories: 'Calories',
    CameraPermissions: 'Camera Permissions',
    CameraPermissionsMessage: 'Cardio Journal needs access to your camera',
    CamPermDenied: 'Camera permission denied',
    Cancel: 'Cancel',
    CantConnectIdentity: "Can't connect to the identity server",
    CantConnectBackend: "Can't connect to backend server",
    CantGoBack: "Can't go back, you need to finish exercise first",
    Comment: 'Comment',
    Complaints: 'Complaints',
    CourseTherapy: 'Course therapy',
    CuffFix: 'Cuff fix',
    December: 'December',
    DeviceId: 'Device id',
    DeviceInstall: 'Device installation',
    DeviceInstalled: 'Device installed',
    Distance: 'Distance',
    Drug: 'Pill',
    Duration: 'Duration',
    Dyspnea: 'Dyspnea',
    EditProfile: 'Edit profile',
    ElectrodeReplacement: 'Electrode replacement',
    EmotionalStress: 'Emotional stress',
    Error: 'Error',
    ErrQR: 'Invalid QR code',
    SameQR: 'This idinv is already set',
    ExerciseFinish: 'Exercise finish',
    ExerciseFinishText: 'Good job! You completed the exercise!',
    Fatigue: 'Fatigue',
    February: 'February',
    Finish: 'Finish',
    FoundLocation: 'Location found!',
    FromEnd: 'From end',
    FromStart: 'From start',
    Good: 'Good',
    Trainer: 'Trainer',
    TrainerType: 'Exercise machine type',
    Walking: 'Walking',
    HaveAGoodSleep: 'Have a good Sleep',
    Headache: 'Headache',
    HeartAreaPain: 'Heart area pain',
    Home: 'Home',
    hour: 'hour',
    hours: 'hours',
    HowDoYouFeelAfterThis: 'How do you feel after this?',
    idinv: 'Investigation ID',
    January: 'January',
    Journal: 'Journal',
    July: 'July',
    June: 'June',
    Locating: 'Looking for location...',
    LocationPermissions: 'Location Permissions',
    LocationPermissionsMessage: 'Cardio Journal needs access to your location',
    Login: 'Login with Incart',
    Logout: 'Logout',
    March: 'March',
    May: 'May',
    Meal: 'Meal',
    MedicineTest: 'Medicine test',
    Meters: 'Meters',
    MicrophonePermissions: 'Microphone Permissions',
    MicrophonePermissionsMessage:
        'Cardio Journal needs access to your microphone',
    minute: 'minute',
    minutes: 'minutes',
    mmHg: 'mmHg',
    Nausea: 'Nausea',
    NegativeEmotions: 'Negative emotions',
    NoConn: 'No Connection',
    NoPhoto: 'No Photo',
    Normal: 'Normal',
    NotFilled: 'Not filled',
    notifText: 'Time to complete the exercise. Tap here to start!',
    NotSelected: 'Not selected',
    November: 'November',
    October: 'October',
    Ok: 'Ok',
    ActiveOrthostasis: 'Active Orthostasis',
    Other: 'Other',
    OtherActivity: 'Other activity',
    OtherComplaints: 'Other',
    OtherEmotions: 'Other emotions',
    OtherLoad: 'Other load (Labor)',
    OtherPain: 'Other pain',
    OtherWeakness: 'Other weakness',
    OverlapMsg: "Can't add the activity, its overlapping with others,",
    OverlapTitle: 'Overlap',
    Pain: 'Pain',
    Palpitation: 'Palpitation',
    password: 'password',
    PhysicalLoad: 'Psysical load',
    PositionalChanges: 'Positional changes',
    PositiveEmotions: 'Positive emotions',
    Postponed: 'Postponed',
    Press: 'Press',
    Pressure: 'Pressure',
    Problems: 'Problems',
    PsychoemotionalTest: 'Psychoemotional test',
    Register: 'Register',
    ReliefOfAttack: 'Relief of attack',
    RemindLater: 'Remind later',
    RetrosternalPain: 'Retrosternal pain',
    Running: 'Running',
    Save: 'Save',
    Saved: 'Saved',
    September: 'September',
    Service: 'Service',
    Settings: 'Settings',
    Sex: 'Sex',
    Shower: 'Shower',
    Sleep: 'Sleep',
    Smoking: 'Smoking',
    Stairs: 'Climbing stairs',
    Start: 'Start',
    Steps: 'Steps',
    StoragePermissions: 'Storage Permissions',
    StoragePermissionsMessage:
        'Cardio Journal needs access to your internal storage',
    Straining: 'Straining',
    Stupefaction: 'Stupefaction',
    Syncope: 'Syncope',
    Tachypnea: 'Tachypnea',
    TakePhoto: 'Take a photo',
    TakingMedicine: 'Medicine',
    Tasks: 'Tasks',
    Terminate: 'Terminate',
    TerminationExerciseQuestion:
        'Do you really want to terminate the exercise? It cannot be undone',
    Tests: 'Tests',
    Time: 'Time',
    Today: 'Today',
    Toilet: 'Toilet',
    Tomorrow: 'Tomorrow',
    Undefined: 'Undefined',
    username: 'username',
    Version: 'Version',
    VerticalPositionCalibration: 'Vertical Position Calibration',
    VisionDisturbances: 'Vision disturbances',
    WalkingTest: '6 min walking test',
    Weakness: 'Weakness',
    WrongPassword: 'Wrong username or password',
    Yesterday: 'Yesterday',
    YouClimbed: 'You climbed',
    YouWalked: 'You walked',
    by: 'by',
    Cycling: 'Exercise bicycle',
    Elliptical: 'Elliptical',
    StairStepper: 'Stair-stepper',
    Joy: 'Joy',
    Sadness: 'Sadness',
    Anger: 'Anger',
    Fear: 'Fear',
    Excitement: 'Excitement',
    Anxiety: 'Anxiety',
    WeightLifting: 'Weight lifting',
    PhysicalLabor: 'Physical labor',
    before: 'before',
    after: 'after',
    BloodPressure: 'Blood pressure',
    NotFilledUp: 'Not filled up',
    Straight: 'Straight',
    LeaningForward: 'Leaning forward',
    LeaningToTheLeft: 'Leaning to the left',
    LeaningToTheRight: 'Leaning to the right',
    DeepBreathing: 'Deep breathing',
    Workout: 'Workout',
    TrainerWalk: 'Treadmill (walk)',
    TrainerRun: 'Treadmill (run)',
    TerminateSleep: 'Do you really want to terminate sleep?',
    ServerDown: 'Identity server down',
    UnknownActivity: 'Unknown activity',
    IdinvFilter: 'IdInv filter',
    Notifications: 'Notifications',
    PostponeNotificationsBy: 'Postpone notifications by (min)',
    State: 'Your well-being',
    CoveredDistance: 'Covered distance',
    AscentTo: 'AscentTo',
    NumberOfSteps: 'Number of steps',
    meters: 'meters',
    steps: 'steps',
    Success: 'Success',
    IdinvChangeSuccess: 'Idinv changed successfully!',
    RegisterSuccess: 'You have successfully registered. Now you can login',
    email: 'email',
    repeatPassword: 'repeat password',
    ErrorUppercase: "Passwords must have at least one uppercase ('A'-'Z')",
    ErrorDigit: "Passwords must have at least one digit ('0'-'9')",
    ErrorAlphanumeric:
        'Passwords must have at least one non alphanumeric character (!@#$%^&*)',
    ErrorPassLen: 'Password must be at least 6 symbols',
    ErrorPassNotEq: 'Passwords are not equal',
    ErrorEmail: 'Email is not valid',
    ErrorFill: 'Fill in all fields',
    ErrorEmailInUse: 'This email is already in use',
    SleepFinishQuestion: 'How was your sleep?',
    SleepFinishTerminateQuestion: 'Do you want to skip the question?',
    Deleted: 'Deleted',
    WaitingPermissions: 'Waiting for permissions...',
    hintPlaceholder: 'Please fill in',
    m: 'm',
}
