export const es = {
    Activity: 'Actividad',
    ActivityEdit: 'Edición de la actividad',
    Alarm: 'Problema',
    Alcohol: 'Alcohol',
    Alert: 'Alerta',
    and: 'y',
    AppTitle: 'Diario de Cardio',
    April: 'Abril',
    Arrhythmia: 'Arritmia',
    AskMeLater: 'Pregúntame luego',
    at: 'a',
    AtivityStats: 'Estadísticas de actividad',
    August: 'Agosto',
    Bad: 'Mal',
    Bicycling: 'Montar en bicicleta',
    Calibrating: 'Calibración',
    Calories: 'Calorías',
    CameraPermissions: 'Permisos de сámera',
    CameraPermissionsMessage: 'Cardio Journal necesita acceso a tu cámara',
    CamPermDenied: 'Permiso de la cámara denegado',
    Cancel: 'Cancelar',
    CantConnectIdentity: 'No se puede conectar al servidor de identidad',
    CantConnectBackend: 'No se puede conectar al servidor de fondo',
    CantGoBack: 'No puedes volver, necesitas terminar el ejercicio primero',
    Comment: 'Comentario',
    Complaints: 'Quejas',
    CourseTherapy: 'Curso de terapia',
    CuffFix: 'Brazalete fijar',
    December: 'Diciembre',
    DeviceId: 'Identificación del dispositivo',
    DeviceInstall: 'Installación del despositivo',
    DeviceInstalled: 'Dispositivo instalado',
    Distance: 'Distancia',
    Drug: 'Postilla',
    Duration: 'Duración',
    Dyspnea: 'Disnea',
    EditProfile: 'Editar perfil',
    ElectrodeReplacement: 'Reemplazo de electrodos',
    EmotionalStress: 'Estrés emocional',
    Error: 'Error',
    ErrQR: 'Código QR inválido',
    SameQR: 'Este idinv ya está configurado',
    ExerciseFinish: 'Ejercicio finalizado',
    ExerciseFinishText: '¡Buen trabajo! ¡Has completado el ejercicio!',
    Fatigue: 'Fatiga',
    February: 'Febrero',
    Finish: 'Terminar',
    FoundLocation: '¡Ubicación encontrada!',
    FromEnd: 'Del final',
    FromStart: 'Del principio',
    Good: 'Bien',
    Trainer: 'Gimnasio',
    TrainerType: 'Tipo de máquina de ejercicio',
    Walking: 'Caminar',
    HaveAGoodSleep: 'Tener un buen descanso',
    Headache: 'Dolor de cabeza',
    HeartAreaPain: 'Dolor en área del corazón',
    Home: 'Principal',
    hour: 'hora',
    hours: 'horas',
    HowDoYouFeelAfterThis: '¿Cómo te sientes después de esto?',
    idinv: 'Identificación de investigación',
    January: 'Jenero',
    Journal: 'Diario',
    July: 'Julio',
    June: 'Junio',
    Locating: '¡Buscando ubicación...',
    LocationPermissions: 'Permisos de ubicación',
    LocationPermissionsMessage: 'Cardio Journal necesita acceso a tu ubicación',
    Login: 'Entrar con Incart',
    Logout: 'Cerrar',
    March: 'Marso',
    May: 'Mayo',
    Meal: 'Comida',
    MedicineTest: 'Prueba de medicina',
    Meters: 'Metros',
    MicrophonePermissions: 'Permisos de micrófono',
    MicrophonePermissionsMessage:
        'Cardio Journal necesita acceso a tu micrófono',
    minute: 'minuto',
    minutes: 'minutos',
    mmHg: 'mmHg',
    Nausea: 'Náusea',
    NegativeEmotions: 'Negativa',
    NoConn: 'Sin conexión',
    NoPhoto: 'No hay foto',
    Normal: 'Normal',
    NotFilled: 'No llenado',
    notifText: 'Tiempo para completar el ejercicio. Toque aquí para comenzar!',
    NotSelected: 'No seleccionado',
    November: 'Noviembre',
    October: 'Octubre',
    Ok: 'Ok',
    ActiveOrthostasis: 'Ortostasis activo',
    Other: 'Otra',
    OtherActivity: 'Otra actividad',
    OtherComplaints: 'Otras quejas',
    OtherEmotions: 'Otras emociones ',
    OtherLoad: 'Otra carga (trabajo)',
    OtherPain: 'Otro dolor',
    OtherWeakness: 'Otra debilidad',
    OverlapMsg: 'No es possible agregar la actividad, se superpone con otras',
    OverlapTitle: 'Superposición',
    Pain: 'Dolor',
    Palpitation: 'Palpitación',
    password: 'contraseña',
    PhysicalLoad: 'Carga fisica',
    PositionalChanges: 'Cambios posicionales',
    PositiveEmotions: 'Positiva',
    Postponed: 'Pospuesto',
    Press: 'Presión',
    Pressure: 'Presión',
    Problems: 'Problemas',
    PsychoemotionalTest: 'Prueba psicoemocional',
    Register: 'Registrarse',
    ReliefOfAttack: 'Alivio del ataque',
    RemindLater: 'Recordar mas tarde',
    RetrosternalPain: 'Dolor retrosternal',
    Running: 'Corriendo',
    Save: 'Salvar',
    Saved: 'Salvado',
    September: 'Septiembre',
    Service: 'Servicio',
    Settings: 'Configuraciones',
    Sex: 'Sexo',
    Shower: 'Ducha',
    Sleep: 'Dormir',
    Smoking: 'Fumar',
    Stairs: 'Escalera',
    Start: 'Comenzar',
    Steps: 'Pasas',
    StoragePermissions: 'Permisos de almacenamiento',
    StoragePermissionsMessage:
        'Cardio Journal necesita acceso a tu almacenamiento',
    Straining: 'Tirante',
    Stupefaction: 'Estupefacción',
    Syncope: 'Síncope',
    Tachypnea: 'Taquipnea',
    TakePhoto: 'Tomar un foto',
    TakingMedicine: 'Pastillas',
    Tasks: 'Tareas',
    Terminate: 'Terninar',
    TerminationExerciseQuestion:
        '¿Realmente quieres terminar el ejercicio? No se puede deshacer',
    Tests: 'Pruebas',
    Time: 'Tiempo',
    Today: 'Hoy',
    Toilet: 'Baño',
    Tomorrow: 'Mañana',
    Undefined: 'Indefinida',
    username: 'nombre de usuario',
    Version: 'Versión',
    VerticalPositionCalibration: 'Calibración de posición vertical',
    VisionDisturbances: 'Trastornos de la visión',
    WalkingTest: 'Prueba de caminata de 6 min',
    Weakness: 'Debilidad',
    WrongPassword: 'Nombre de usuario o contraseña incorrectos',
    Yesterday: 'Ayer',
    YouClimbed: 'Usted subió',
    YouWalked: 'Usted caminó',
    by: 'por',
    Cycling: 'Bicicleta de ejercicios',
    Elliptical: 'Entrenador eliptico',
    StairStepper: 'Entrenador de pasos',
    Joy: 'Alegría',
    Sadness: 'Tristeza',
    Anger: 'Enfado',
    Fear: 'Miedo',
    Excitement: 'Excitación',
    Anxiety: 'Ansiedad',
    WeightLifting: 'Levantamiento de pesas',
    PhysicalLabor: 'Trabajo físico',
    before: 'antes',
    after: 'después',
    BloodPressure: 'Presión sanguínea',
    NotFilledUp: 'No lleno',
    Straight: 'Derecho',
    LeaningForward: 'Inclinado hacia adelante',
    LeaningToTheLeft: 'Inclinado hacia la izquierda',
    LeaningToTheRight: 'Inclinado hacia la derecha',
    DeepBreathing: 'Respiración profunda',
    Workout: 'Rutina de ejercicio',
    TrainerWalk: 'Rueda de andar: caminar',
    TrainerRun: 'Rueda de andar: correr',
    TerminateSleep: 'De verdad quieres terminar el sueño??',
    ServerDown: 'Servidor de identidad inactivo',
    UnknownActivity: 'Actividad desconocida',
    IdinvFilter: 'Filtrar de Idinv',
    Notifications: 'Notificaciones',
    PostponeNotificationsBy: 'Posponer las notificaciones por (min)',
    State: 'Su bienestar',
    CoveredDistance: 'Distancia cubierta',
    AscentTo: 'Ascenso a',
    NumberOfSteps: 'Numero de pasos',
    meters: 'metros',
    steps: 'pasos',
    Success: 'Éxito',
    IdinvChangeSuccess: '¡Idinv cambió con éxito!',
    RegisterSuccess:
        'Se ha registrado exitosamente. Ahora puedes iniciar sesión',
    email: 'email',
    repeatPassword: 'repite la contraseña',
    ErrorUppercase:
        "Las contraseñas deben tener al menos una mayúscula ('A' - 'Z')",
    ErrorDigit: "Las contraseñas deben tener al menos un dígito ('0'-'9')",
    ErrorAlphanumeric:
        'Las contraseñas deben tener al menos un carácter no alfanumérico (!@#$%^&*)',
    ErrorPassLen: 'La contraseña debe tener al menos 6 símbolos',
    ErrorPassNotEq: 'Las contraseñas no son iguales',
    ErrorEmail: 'El correo electrónico no es válido',
    ErrorFill: 'Completa todos los campos',
    ErrorEmailInUse: 'Este correo electrónico ya está en uso',
    SleepFinishQuestion: '¿Como estuvo tu sueño?',
    SleepFinishTerminateQuestion: '¿Desea omitir la pregunta?',
    Deleted: 'Eliminado',
    WaitingPermissions: 'Esperando permisos...',
    hintPlaceholder: 'Por favor, complete',
    m: 'm',
    ReqLocation: 'Solicitando la ubicación...',
    Editing: 'Edición de',
    CantEdit: `No puedes editar`,
    AppStatus: 'Estado de la aplicación',
    Barometer: 'Barómetro',
    Pedometer: 'Podómetro',
    FilesStored: 'Archivos almacenados',
    Camera: 'Cámara',
    Microphone: 'Micrófono',
    Geolocation: 'Geolocalización',
    ReadStorage: 'Leer almacenamiento',
    WriteStorage: 'Almacenamiento de escritura',
    Sensors: 'Sensores',
    Permissions: 'Permisos',
    Storage: 'Almacenamiento',
    Connectivity: 'Conectividad',
}
