export const ru = {
    Activity: 'Активность',
    ActivityEdit: 'Редактирование активности',
    Alarm: 'Тревога',
    Alcohol: 'Алкоголь',
    Alert: 'Внимание',
    and: 'и',
    AppTitle: 'Кардиожурнал',
    April: 'Апреля',
    Arrhythmia: 'Перебои (Аритмия)',
    AskMeLater: 'Спросить позже',
    at: 'в',
    AtivityStats: 'Статистика активности',
    August: 'Августа',
    Bad: 'Плохо',
    Bicycling: 'Велосипед',
    Calibrating: 'Калибровка',
    Calories: 'Калории',
    CameraPermissions: 'Разрешение на использование камеры',
    CameraPermissionsMessage: 'Cardio Journal нужен доступ к камере',
    CamPermDenied: 'Отказано в использовании камеры',
    Cancel: 'Отменить',
    CantConnectIdentity: 'Невозможно соединиться с сервером индентификации',
    CantConnectBackend: 'Невозможно соединиться с бэкенд сервером',
    CantGoBack: 'Нельзя вернуться, сначала закончите задание',
    Comment: 'Комментарий',
    Complaints: 'Жалобы',
    CourseTherapy: 'Курсовая терапия',
    CuffFix: 'Повторное наложение манжеты',
    December: 'Декабря',
    DeviceId: 'Номер устройства',
    DeviceInstall: 'Установка прибора',
    DeviceInstalled: 'Устройство установлено',
    Distance: 'Расстояние',
    Drug: 'Препарат',
    Duration: 'Длительность',
    Dyspnea: 'Одышка',
    EditProfile: 'Редактировать профиль',
    ElectrodeReplacement: 'Замена электрода',
    EmotionalStress: 'Эмоциональная нагрузка',
    Error: 'Ошибка',
    ErrQR: 'Неверный QR код',
    SameQR: 'Этот idinv уже установлен',
    ExerciseFinish: 'Завершение задания',
    ExerciseFinishText: 'Поздравляем, вы справились с заданием!',
    Nausea: 'Дурнота (Тошнота)',
    Fatigue: 'Усталость',
    February: 'Февраля',
    Finish: 'Завершить',
    FoundLocation: 'Местоположение найдено!',
    FromEnd: 'Время конца',
    FromStart: 'Время начала',
    Good: 'Хорошо',
    Trainer: 'Тренажёр',
    TrainerType: 'Тип тренажёра',
    Walking: 'Ходьба',
    HaveAGoodSleep: 'Приятного отдыха',
    Headache: 'Головная боль',
    HeartAreaPain: 'Боль в области сердца',
    Home: 'Дом',
    hour: 'час',
    hours: 'часов',
    HowDoYouFeelAfterThis: 'Как вы себя чувствуете после этого?',
    idinv: 'Номер обследования',
    January: 'Января',
    Journal: 'Дневник',
    July: 'Июля',
    June: 'Июня',
    Locating: 'Поиск местоположения...',
    LocationPermissions: 'Разрешение на использование геолокации',
    LocationPermissionsMessage: 'Cardio Journal нужен доступ к геолокации',
    Login: 'Войти с Инкарт',
    Logout: 'Выйти',
    March: 'Марта',
    May: 'Мая',
    Meal: 'Еда',
    MedicineTest: 'Тестируемый препарат',
    Meters: 'Метров',
    MicrophonePermissions: 'Разрешение на использование микрофона',
    MicrophonePermissionsMessage: 'Cardio Journal нужен доступ к микрофону',
    minute: 'минута',
    minutes: 'минут',
    mmHg: 'мм рт.ст.',
    NegativeEmotions: 'Негативные эмоции',
    NoConn: 'Нет соединения',
    NoPhoto: 'Нет фото',
    Normal: 'Нормально',
    NotFilled: 'Не заполнено',
    notifText: 'Время выполнить задание. Нажмите, чтобы начать!',
    NotSelected: 'Не выбрано',
    November: 'Ноября',
    October: 'Октября',
    Ok: 'Ок',
    ActiveOrthostasis: 'Активный ортостаз',
    Other: 'Другое',
    OtherActivity: 'Другая активность',
    OtherComplaints: 'Другие жалобы',
    OtherEmotions: 'Другие эмоции',
    OtherLoad: 'Другая нагрузка (Работа)',
    OtherPain: 'Другая боль',
    OtherWeakness: 'Другие варианты слабости',
    OverlapMsg: 'Невозможно добавить активность, она пересекается с другими',
    OverlapTitle: 'Наложение',
    Pain: 'Боль',
    Palpitation: 'Сердцебиение (Пульсация)',
    password: 'пароль',
    PhysicalLoad: 'Физическая нагрузка',
    PositionalChanges: 'Изменения положения',
    PositiveEmotions: 'Позитивные эмоции',
    Postponed: 'Отложено',
    Press: 'Жим',
    Pressure: 'Давление',
    Problems: 'Проблемы',
    PsychoemotionalTest: 'Психоэмоц. пробы',
    Register: 'Зарегистрироваться',
    ReliefOfAttack: 'Купирование приступа',
    RemindLater: 'Напомнить позже',
    RetrosternalPain: 'Боль за грудиной',
    Running: 'Бег',
    Save: 'Сохранить',
    Saved: 'Сохранено',
    September: 'Сентября',
    Service: 'Сервис',
    Settings: 'Настройки',
    Sex: 'Секс',
    Shower: 'Душ',
    Sleep: 'Сон',
    Smoking: 'Курение',
    Stairs: 'Подъём по лестнице',
    Start: 'Начать',
    Steps: 'Шаги',
    StoragePermissions: 'Разрешение на хранение данных',
    StoragePermissionsMessage:
        'Cardio Journal нужен доступ к внутреннему хранилищу',
    Straining: 'Натуживание',
    Stupefaction: 'Помрачнение сознания',
    Syncope: 'Обморок',
    Tachypnea: 'Учащённое дыхание',
    TakePhoto: 'Сделать фото',
    TakingMedicine: 'Лекарства',
    Tasks: 'Задания',
    Terminate: 'Прервать',
    TerminationExerciseQuestion:
        'Вы действительно хотите прервать задание? Это необратимое действие',
    Tests: 'Пробы',
    Time: 'Время',
    Today: 'Сегодня',
    Toilet: 'Tуалет',
    Tomorrow: 'Завтра',
    Undefined: 'Без названия',
    username: 'имя пользователя',
    Version: 'Версия',
    VerticalPositionCalibration: 'Калибровка вертикального положения',
    VisionDisturbances: 'Нарушения зрения',
    WalkingTest: 'Тест с 6-мин. ходьбой',
    Weakness: 'Слабость',
    WrongPassword: 'Неправильный логин или пароль',
    Yesterday: 'Вчера',
    YouClimbed: 'Вы поднялись на',
    YouWalked: 'Вы прошли',
    by: 'на',
    Cycling: 'Велотренажёр',
    Elliptical: 'Эллиптический',
    StairStepper: 'Лестничный',
    Joy: 'Радость',
    Sadness: 'Печаль',
    Anger: 'Гнев',
    Fear: 'Страх',
    Excitement: 'Волнение',
    Anxiety: 'Тревога',
    WeightLifting: 'Подъём тяжестей',
    PhysicalLabor: 'Физическая работа',
    before: 'до',
    after: 'после',
    BloodPressure: 'Давление',
    NotFilledUp: 'Не заполнено',
    Straight: 'Прямо',
    LeaningForward: 'Нагнувшись вперёд',
    LeaningToTheLeft: 'Нагнувшись влево',
    LeaningToTheRight: 'Нагнувшись вправо',
    DeepBreathing: 'Глубокое дыхание',
    Workout: 'Тренировка',
    TrainerWalk: 'Бегущая дорожка (ходьба)',
    TrainerRun: 'Бегущая дорожка (бег)',
    TerminateSleep: 'Вы действительно хотите завершить сон?',
    ServerDown: 'Сервер индетификации недоступен',
    UnknownActivity: 'Неизвестная активность',
    IdinvFilter: 'Фильтр по № обследования',
    Notifications: 'Уведомления',
    PostponeNotificationsBy: 'Отложить уведомление на (мин)',
    State: 'Ваше состояние',
    CoveredDistance: 'Пройденное расстояние',
    AscentTo: 'Подъём на',
    NumberOfSteps: 'Сделано шагов',
    meters: 'метров',
    steps: 'шагов',
    Success: 'Успех',
    IdinvChangeSuccess: 'Idinv успешно изменён',
    RegisterSuccess: 'Вы успешно зарегистрировались. Теперь вы можете войти',
    email: 'электронная почта',
    repeatPassword: 'повторите пароль',
    ErrorUppercase: 'Пароль должен содержать хотя бы одну заглавную букву',
    ErrorDigit: 'Пароль должен содержать хотя бы одну цифру',
    ErrorAlphanumeric:
        'Пароль долежен содержать хотя бы один символ (!"№;%:?*)',
    ErrorPassLen: 'Пароль должен быть не менее 6 символов',
    ErrorPassNotEq: 'Пароли не совпадают',
    ErrorEmail: 'Неправильная электронная почта',
    ErrorFill: 'Заполните поля',
    ErrorEmailInUse: 'Пользователь с этой почтой уже зарегистрирован',
    SleepFinishQuestion: 'Как вы спали?',
    SleepFinishTerminateQuestion: 'Вы хотите пропустить выбор?',
}
